---
title: "A crash course on gravity models"
author: "Mauricio Vargas"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: ../inst/REFERENCES.bib
vignette: >
  %\VignetteIndexEntry{A crash course on gravity models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE, tidy = FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

## Basic model

Gravity models in their traditional form are inspired by Newton law of gravitation: 

$$
F_{ij}=G\frac{M_{i}M_{j}}{D^{2}_{ij}}.
$$
	
The force $F$ between two bodies $i$ and $j$ with $i \neq j$ is proportional to the masses $M$ of these bodies and inversely proportional to the square of their geographical distance $D$. $G$ is a constant and as such of no major concern.
	
The underlying idea of a traditional gravity model, shown for international trade, is equally simple: 
	
$$
X_{ij}=G\frac{Y_{i}^{\beta_{1}}Y_{j}^{\beta_{2}}}{D_{ij}^{\beta_{3}}}. 
$$

The trade flow $X$ is explained by $Y_{i}$ and $Y_{j}$ that are the masses of the exporting and importing country (e.g. the GDP) and $ D_{ij}$ that is the distance between the countries.

Dummy variables such as common borders $contig$ or regional trade agreements $rta$ can be added to the model. Let $t_{ij}$ be the transaction cost defined as:

$$
t_{ij}=\exp(contig_{ij} + rta_{ij})
$$
  
So that the model with frictions is now:

$$
X_{ij}=G\frac{Y_{i}^{\beta_{1}}Y_{j}^{\beta_{2}}}{D_{ij}^{\beta_{3}}}t_{ij}^{\beta_4}. 
$$

A logarithmic operator can be applied to form a log-linear model and use a standard estimation methods such as OLS:

$$
\log X_{ij}=\beta_{0}\log G +\beta_{1}\log Y_{i}+\beta_{2}\log Y_{j}+\beta_{3}\log D_{ij}+\beta_{4}contig_{ij}+\beta_{5}rta_{ij}
$$

## Trade barriers model

Provided trade barriers exists, the econometric literature proposes the Multilateral Resistance model defined by the equations:

$$
X_{ij}=\frac{Y_{i}Y_{j}}{Y}\frac{t_{ij}^{1-\sigma}}{P_{j}^{1-\sigma}\Pi_{i}^{1-\sigma}}
$$
with
$$
\Pi_{i}^{1-\sigma}=\sum_{j}\frac{t_{ij}^{1-\sigma}}{P_{j}^{1-\sigma}}\frac{Y_{j}}{Y}
$$
and
$$
P_{j}^{1-\sigma}=\sum_{i}\frac{t_{ij}^{1-\sigma}}{\Pi_{i}^{1-\sigma}}\frac{Y_{i}}{Y}.
$$
	
Basically the model proposes that the exports $X_{ij}$ from $i$ to $j$ are determined by the supply factors in $i$, $Y_{i}$, and the demand factors in $ j $, $Y_{j}$, as well as the transaction costs $t_{ij}$. 

Next to information on bilateral partners $i$ and $j$, information on the rest of the world is included in the gravity model with $Y=\sum_{i} Y_{i}= \sum_{j} Y_{j}$ that represents the worldwide sum of incomes (e.g. the world's GDP). 

$\sigma$ represents the elasticity of substitution between all goods with $\sigma > 1$ in order to account for the preference for a variation of goods (e.g. in this model goods can be replaced for other similar goods).

The Multilateral Resistance terms are included via the terms $P$, Inward Multilateral Resistance, and $\Pi$, Outward Multilateral Resistance. The Outward Multilateral Resistance $\Pi_{i}$ is a function of the transaction costs of $i$ to all trade partners $j$ and their demand, $P_{j}$.

The Multilateral Resistance terms dependent on each other. Hence, the estimation of structural gravity models becomes complex.

## Model estimation

To estimate gravity equations you need a square dataset including bilateral flows defined by the argument \code{dependent_variable}, a distance measure defined by the argument \code{distance} that is the key regressor, and other potential influences (e.g. contiguity and common currency) given as a vector in \code{additional_regressors} are required.

Some estimation methods require ISO codes or similar of type character variables to compute particular country effects. Make sure the origin and destination codes are of type "character".

The rule of thumb for regressors or independent variables consists in:

* All dummy variables should be of type numeric (0/1). 
* If an independent variable is defined as a ratio, it should be logged.

The user should perform some data cleaning beforehand to remove observations that contain entries that
can distort estimates, notwithstanding the functions provided within this package will remove zero flows and distances.

See \href{https://sites.google.com/site/hiegravity/}{Gravity Equations: Workhorse, Toolkit, and Cookbook}
for gravity datasets and Stata code for estimating gravity models.

## References

For more information on gravity models, theoretical foundations and
estimation methods in general see

\insertRef{Anderson1979}{gravity}

\insertRef{Anderson2001}{gravity}

\insertRef{Anderson2010}{gravity}

\insertRef{Baier2009}{gravity}

\insertRef{Baier2010}{gravity}

\insertRef{Feenstra2002}{gravity}

\insertRef{Head2010}{gravity}

\insertRef{Head2014}{gravity}

\insertRef{Santos2006}{gravity}

and the citations therein.

See \href{https://sites.google.com/site/hiegravity/}{Gravity Equations: Workhorse, Toolkit, and Cookbook} for gravity datasets and Stata code for estimating gravity models.

For estimating gravity equations using panel data see

\insertRef{Egger2003}{gravity}

\insertRef{Gomez-Herrera2013}{gravity}

and the references therein.
